import { useState, useRef, useCallback } from 'react'
import type { AIPurpose, AIMessage, AIConversation } from '@/schemas/ai.ts'
import { AIClient } from '@/lib/ai/client.ts'
import { buildGameContext, buildSystemPrompt } from '@/lib/ai/prompts.ts'
import { useSessionStore } from '@/stores/session-store.ts'
import { useAISettings } from './use-ai-settings.ts'
import { generateId } from '@/lib/utils/id.ts'
import { PURPOSE_LABELS } from '@/lib/ai/prompts.ts'

export function useAI() {
  const {
    settings,
    activeProvider,
    updateSettings,
  } = useAISettings()

  const [streamingText, setStreamingText] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [lastResponse, setLastResponse] = useState<string | null>(null)
  const [conversation, setConversation] = useState<AIConversation | null>(null)

  const abortControllerRef = useRef<AbortController | null>(null)
  const streamBufferRef = useRef('')
  const rafIdRef = useRef<number | null>(null)
  const clientRef = useRef(new AIClient())

  // --- Conversation management -----------------------------------------------

  const startNewConversation = useCallback((purpose: AIPurpose | null) => {
    if (purpose === null) {
      setConversation(null)
      setLastResponse(null)
      setError(null)
      setStreamingText('')
      return
    }
    const newConversation: AIConversation = {
      id: generateId(),
      title: PURPOSE_LABELS[purpose],
      createdAt: Date.now(),
      messages: [],
      purpose,
    }
    setConversation(newConversation)
    setLastResponse(null)
    setError(null)
    setStreamingText('')
  }, [])

  // --- Abort -----------------------------------------------------------------

  const abort = useCallback(() => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
      abortControllerRef.current = null
    }
    if (rafIdRef.current !== null) {
      cancelAnimationFrame(rafIdRef.current)
      rafIdRef.current = null
    }
    setIsGenerating(false)
    setStreamingText('')
    streamBufferRef.current = ''
  }, [])

  // --- Post to shared chat ---------------------------------------------------

  const postToChat = useCallback((text: string) => {
    const message = {
      id: generateId(),
      senderId: 'system',
      senderName: 'AI Assistant',
      type: 'ai_response' as const,
      content: text,
      timestamp: Date.now(),
      isPublic: true,
    }
    useSessionStore.getState().addChatMessage(message)
  }, [])

  // --- Token tracking helper -------------------------------------------------

  const trackTokenUsage = useCallback(
    (tokensUsed: number) => {
      updateSettings({
        tokenUsage: {
          session: settings.tokenUsage.session + tokensUsed,
          lifetime: settings.tokenUsage.lifetime + tokensUsed,
        },
      })
    },
    [settings.tokenUsage, updateSettings],
  )

  // --- Save conversation to session store ------------------------------------

  const saveConversationToStore = useCallback(
    (conv: AIConversation) => {
      const store = useSessionStore.getState()
      if (!store.session) return

      const existing = store.session.aiConversations
      const index = existing.findIndex((c) => c.id === conv.id)

      const updated =
        index >= 0
          ? existing.map((c) => (c.id === conv.id ? conv : c))
          : [...existing, conv]

      // Directly mutate via store set — session store uses immer
      useSessionStore.setState((state) => {
        if (state.session) {
          state.session.aiConversations = updated
        }
      })
    },
    [],
  )

  // --- Generate --------------------------------------------------------------

  const generate = useCallback(
    async (purpose: AIPurpose, userPrompt: string, generateOptions?: { autoGenerated?: boolean }) => {
      // 1. Get session & build context
      const session = useSessionStore.getState().session
      if (!session) {
        setError('No active session. Start a session first.')
        return
      }

      // 2-3. Build game context and system prompt
      const context = buildGameContext(session)
      const systemPrompt = buildSystemPrompt(
        purpose,
        context,
        settings.customSystemPrompt,
      )

      // 4. Validate active provider
      if (!activeProvider) {
        setError('No AI provider configured. Add a provider in AI Settings.')
        return
      }

      // Reset state
      setError(null)
      setIsGenerating(true)
      setStreamingText('')
      setLastResponse(null)
      streamBufferRef.current = ''

      // 5. Build conversation if one doesn't exist or purpose changed
      let currentConv = conversation
      if (!currentConv || currentConv.purpose !== purpose) {
        currentConv = {
          id: generateId(),
          title: PURPOSE_LABELS[purpose],
          createdAt: Date.now(),
          messages: [],
          purpose,
          gameContext: context,
        }
      }

      // 6. Build messages array
      const systemMessage: AIMessage = {
        role: 'system',
        content: systemPrompt,
        timestamp: Date.now(),
      }

      const userMessage: AIMessage = {
        role: 'user',
        content: userPrompt,
        timestamp: Date.now(),
        isAutoGenerated: generateOptions?.autoGenerated,
      }

      // Full messages for the API: system + conversation history + new user message
      const apiMessages = [
        { role: systemMessage.role, content: systemMessage.content },
        ...currentConv.messages
          .filter((m) => m.role !== 'system')
          .map((m) => ({ role: m.role, content: m.content })),
        { role: userMessage.role, content: userMessage.content },
      ]

      // 7. Token estimation for non-free providers
      if (!activeProvider.isFree) {
        const estimatedTokens = Math.ceil(
          apiMessages.reduce((sum, m) => sum + m.content.length, 0) / 4,
        )
        console.log(
          `[AI] Estimated prompt tokens: ~${estimatedTokens} (provider: ${activeProvider.name})`,
        )
      }

      const options = {
        temperature: settings.temperature,
        maxTokens: settings.maxTokens,
      }

      try {
        let responseText = ''
        let tokensUsed = 0

        if (settings.enableStreaming) {
          // 8. Streaming path
          abortControllerRef.current = new AbortController()

          const stream = clientRef.current.chatStream(
            apiMessages,
            activeProvider,
            options,
            abortControllerRef.current.signal,
          )

          for await (const chunk of stream) {
            streamBufferRef.current += chunk

            // Batch UI updates via requestAnimationFrame
            if (rafIdRef.current === null) {
              rafIdRef.current = requestAnimationFrame(() => {
                setStreamingText(streamBufferRef.current)
                rafIdRef.current = null
              })
            }
          }

          // Flush any remaining buffered text
          if (rafIdRef.current !== null) {
            cancelAnimationFrame(rafIdRef.current)
            rafIdRef.current = null
          }

          responseText = streamBufferRef.current
          setStreamingText('')
          streamBufferRef.current = ''

          // Estimate tokens for streaming (no usage data from stream)
          tokensUsed = Math.ceil(
            (apiMessages.reduce((sum, m) => sum + m.content.length, 0) +
              responseText.length) /
              4,
          )
        } else {
          // 9. Non-streaming path
          const result = await clientRef.current.chat(
            apiMessages,
            activeProvider,
            options,
          )

          responseText = result.content
          tokensUsed = result.tokensUsed?.total ?? Math.ceil(
            (apiMessages.reduce((sum, m) => sum + m.content.length, 0) +
              responseText.length) /
              4,
          )
        }

        setLastResponse(responseText)

        // 10. Update token usage
        trackTokenUsage(tokensUsed)

        // 11. Update conversation with new messages
        const assistantMessage: AIMessage = {
          role: 'assistant',
          content: responseText,
          timestamp: Date.now(),
        }

        const updatedConv: AIConversation = {
          ...currentConv,
          gameContext: context,
          messages: [...currentConv.messages, userMessage, assistantMessage],
        }

        setConversation(updatedConv)
        saveConversationToStore(updatedConv)
      } catch (err: unknown) {
        // 12. Error handling
        if (err instanceof DOMException && err.name === 'AbortError') {
          // User cancelled — not an error
          return
        }

        const message = err instanceof Error ? err.message : String(err)
        setError(message)
      } finally {
        setIsGenerating(false)
        abortControllerRef.current = null
      }
    },
    [
      settings.customSystemPrompt,
      settings.temperature,
      settings.maxTokens,
      settings.enableStreaming,
      activeProvider,
      conversation,
      trackTokenUsage,
      saveConversationToStore,
    ],
  )

  return {
    generate,
    streamingText,
    isGenerating,
    error,
    abort,
    lastResponse,
    conversation,
    startNewConversation,
    postToChat,
  }
}
