import type { DangerLevel } from './reference.ts';
import type { StoreType } from './stores.ts';

// ========== Provider Configuration ==========

export type AIProviderType = 'ollama' | 'openai-compatible';

export interface AIProviderConfig {
  id: string;
  name: string;                          // "My Ollama", "OpenAI", etc.
  type: AIProviderType;
  endpoint: string;                      // "http://localhost:11434" or "https://api.openai.com"
  apiKey?: string;                       // only for paid/authenticated providers
  model: string;                         // "llama3.2", "gpt-4o-mini", etc.
  isFree: boolean;                       // controls cost warnings — true for Ollama, user-set for others
}

export interface AISettings {
  providers: AIProviderConfig[];
  activeProviderId?: string;
  temperature: number;                   // 0.0-2.0, default 0.7
  maxTokens: number;                     // default 1000
  enableStreaming: boolean;              // default true
  ollamaAutoDetect: boolean;            // default true
  customSystemPrompt?: string;
  tokenUsage: {
    session: number;
    lifetime: number;
  };
}

export const DEFAULT_AI_SETTINGS: AISettings = {
  providers: [],
  activeProviderId: undefined,
  temperature: 0.7,
  maxTokens: 1000,
  enableStreaming: true,
  ollamaAutoDetect: true,
  customSystemPrompt: undefined,
  tokenUsage: { session: 0, lifetime: 0 },
};

// ========== Conversation & Messages ==========

export type AIPurpose =
  | 'encounter_description'
  | 'npc_dialogue'
  | 'adventure_hook'
  | 'ruling_help'
  | 'treasure_description'
  | 'store_generation'
  | 'room_description'
  | 'trap_description'
  | 'general';

export interface AIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  timestamp: number;
  isAutoGenerated?: boolean;
}

export interface AIConversation {
  id: string;
  title: string;
  createdAt: number;
  messages: AIMessage[];
  purpose: AIPurpose;
  gameContext?: AIGameContext;
}

// ========== Game Context ==========

export interface AIMonsterContext {
  name: string;
  description?: string;                 // e.g. "A scarred veteran of the underground..."
  level: number;
  ac: number;
  currentHp: number;
  maxHp: number;
  attacks: string[];                    // e.g. "Longsword +3 (1d8+1)"
  abilities: string[];                  // e.g. "Call for Backup: Can blow a whistle..."
  tags: string[];                       // e.g. ["humanoid", "guard"]
}

export interface AIPartyMemberContext {
  name: string;                          // character name, NOT player name
  ancestry: string;
  class: string;
  level: number;
}

export interface AIGameContext {
  partyLevel: number;
  partySize: number;
  partyMembers: AIPartyMemberContext[];
  partyAncestries: string[];
  partyClasses: string[];
  inCombat: boolean;
  activeMonsters?: AIMonsterContext[];
  currentLocation?: string;
  currentDangerLevel?: DangerLevel;
  isInDarkness: boolean;
  activeLightSources?: string[];        // e.g. ["Torch (42 min remaining)"]
  recentEvents?: string[];
}

// ========== Request/Result Tracking ==========

export interface AIGenerationRequest {
  purpose: AIPurpose;
  prompt: string;
  context?: AIGameContext;
  responseFormat?: 'text' | 'json';
  storeType?: StoreType;
  monsters?: string[];
}

export interface AIGenerationResult {
  id: string;
  request: AIGenerationRequest;
  rawResponse: string;
  parsedData?: unknown;
  timestamp: number;
  tokensUsed: {
    prompt: number;
    completion: number;
    total: number;
  };
}

// ========== Ollama-specific types ==========

export interface OllamaModel {
  name: string;
  size: number;
  digest: string;
  modified_at: string;
}

export interface OllamaTagsResponse {
  models: OllamaModel[];
}
