import { useState, useRef, useEffect, useCallback } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { useAI } from '@/hooks/use-ai.ts'
import { useAISettings } from '@/hooks/use-ai-settings.ts'
import { useLocale } from '@/hooks/use-locale.ts'
import { PURPOSE_LABELS, PURPOSE_LABEL_KEYS, PURPOSE_ICONS } from '@/lib/ai/prompts.ts'
import { useSessionStore } from '@/stores/session-store.ts'
import type { AIPurpose } from '@/schemas/ai.ts'

function renderMarkdown(text: string) {
  const parts: (string | React.ReactElement)[] = []
  // Split by **bold** and *italic* patterns
  const regex = /(\*\*(.+?)\*\*|\*(.+?)\*)/g
  let lastIndex = 0
  let match: RegExpExecArray | null
  let key = 0

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push(text.slice(lastIndex, match.index))
    }
    if (match[2]) {
      // **bold**
      parts.push(<strong key={key++} className="font-semibold">{match[2]}</strong>)
    } else if (match[3]) {
      // *italic*
      parts.push(<em key={key++}>{match[3]}</em>)
    }
    lastIndex = match.index + match[0].length
  }
  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex))
  }
  return parts
}

// Default prompts per purpose for quick actions
const DEFAULT_PROMPTS: Record<AIPurpose, string> = {
  encounter_description: 'Describe the current encounter',
  npc_dialogue: 'Create an NPC the party encounters',
  adventure_hook: 'Generate an adventure hook for this party',
  ruling_help: 'I need help with a ruling during this session. Acknowledge the current scene briefly and ask me what specific situation I need a ruling on.',
  treasure_description: 'Describe the treasure the party finds',
  store_generation: 'Generate a shop the party can visit',
  room_description: 'Describe the room the party enters',
  trap_description: 'Design a trap for the party to encounter',
  general: '',
}

interface AIPanelProps {
  isOpen: boolean
  onClose: () => void
}

export function AIPanel({ isOpen, onClose }: AIPanelProps) {
  const { t, ti } = useLocale()
  const navigate = useNavigate()
  const {
    generate,
    streamingText,
    isGenerating,
    error,
    abort,
    lastResponse,
    conversation,
    startNewConversation,
    postToChat,
  } = useAI()

  const { settings, activeProvider } = useAISettings()

  const [inputValue, setInputValue] = useState('')
  const [sceneContext, setSceneContext] = useState('')
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Auto-scroll conversation to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [conversation?.messages.length, streamingText])

  // Focus textarea when panel opens
  useEffect(() => {
    if (isOpen && textareaRef.current) {
      setTimeout(() => textareaRef.current?.focus(), 200)
    }
  }, [isOpen])

  // Auto-resize textarea
  const resizeTextarea = useCallback(() => {
    const ta = textareaRef.current
    if (!ta) return
    ta.style.height = 'auto'
    ta.style.height = Math.min(ta.scrollHeight, 120) + 'px'
  }, [])

  useEffect(() => {
    resizeTextarea()
  }, [inputValue, resizeTextarea])

  const handleSend = useCallback(() => {
    const text = inputValue.trim()
    if (!text || isGenerating) return
    const purpose = conversation?.purpose ?? 'general'
    setInputValue('')
    generate(purpose, text)
  }, [inputValue, isGenerating, conversation, generate])

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        handleSend()
      }
    },
    [handleSend],
  )

  const handleQuickAction = useCallback(
    (purpose: AIPurpose) => {
      startNewConversation(purpose)

      const scene = sceneContext.trim()
      const contextSuffix = scene ? `\n\nSCENE CONTEXT (use this to set the stage):\n${scene}` : ''

      const session = useSessionStore.getState().session
      const hasMonsters =
        session &&
        Object.values(session.activeMonsters).some((m) => !m.isDefeated)

      // Build the prompt
      const monsterNames = session ? Object.values(session.activeMonsters).filter(m => !m.isDefeated).map(m => m.name) : []
      const prompt =
        purpose === 'encounter_description' && hasMonsters
          ? `Describe this encounter. There are exactly ${monsterNames.length} enemies: ${monsterNames.join(', ')}. Describe each one and how they appear.${contextSuffix}`
          : `${DEFAULT_PROMPTS[purpose]}${contextSuffix}`

      // Always auto-generate immediately
      setInputValue('')
      generate(purpose, prompt, { autoGenerated: true })
    },
    [startNewConversation, generate, sceneContext],
  )

  const isFreeProvider = activeProvider?.isFree ?? false

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/30"
          onClick={onClose}
        />
      )}

      {/* Panel */}
      <div
        className={`fixed right-0 top-0 z-50 flex h-full w-96 flex-col border-l border-border bg-card shadow-xl transition-transform duration-200 ${
          isOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-4 py-3">
          <div className="flex items-center gap-2">
            <h2 className="font-semibold">{t('ai.title')}</h2>
            <span
              className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${
                isFreeProvider
                  ? 'bg-green-500/20 text-green-400'
                  : 'bg-amber-500/20 text-amber-400'
              }`}
            >
              {isFreeProvider ? t('ai.free') : t('ai.paid')} &middot;{' '}
              {ti('ai.tokensUsed', { count: settings.tokenUsage.session.toLocaleString() })}
            </span>
          </div>
          <div className="flex items-center gap-1">
            {conversation && (
              <button
                onClick={() => startNewConversation(null)}
                className="rounded-md px-2 py-1 text-xs text-muted-foreground hover:bg-accent hover:text-foreground"
                title={t('ai.backToQuickActions')}
              >
                {t('common.new')}
              </button>
            )}
            <button
              onClick={onClose}
              className="rounded-md px-2 py-1 text-lg text-muted-foreground hover:bg-accent hover:text-foreground"
            >
              &times;
            </button>
          </div>
        </div>

        {/* No provider configured */}
        {!activeProvider ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-4 px-6 text-center">
            <p className="text-sm text-muted-foreground">
              {t('ai.setupProvider')}
            </p>
            <button
              onClick={() => navigate({ to: '/gm/settings' })}
              className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90"
            >
              {t('ai.openSettings')}
            </button>
          </div>
        ) : (
          <>
            {/* Quick Actions */}
            {!conversation && (
              <div className="border-b border-border px-4 py-3">
                <p className="mb-2 text-xs font-medium text-muted-foreground">
                  {t('ai.quickActions')}
                </p>
                <div className="grid grid-cols-2 gap-1.5">
                  {(Object.keys(PURPOSE_LABEL_KEYS) as AIPurpose[]).filter(
                    (p) => p !== 'treasure_description' && p !== 'general'
                  ).map(
                    (purpose) => (
                      <button
                        key={purpose}
                        onClick={() => handleQuickAction(purpose)}
                        disabled={isGenerating}
                        className="flex items-center gap-1.5 rounded-md border border-border/50 px-2.5 py-1.5 text-left text-xs transition hover:bg-accent disabled:opacity-50"
                      >
                        <span>{PURPOSE_ICONS[purpose]}</span>
                        <span className="truncate">
                          {t(PURPOSE_LABEL_KEYS[purpose])}
                        </span>
                      </button>
                    ),
                  )}
                </div>
                <div className="mt-3">
                  <label className="mb-1 block text-[10px] font-medium text-muted-foreground">
                    {t('ai.sceneContext')} <span className="font-normal">{t('ai.sceneContextHint')}</span>
                  </label>
                  <textarea
                    value={sceneContext}
                    onChange={(e) => setSceneContext(e.target.value)}
                    placeholder={t('ai.sceneContextPlaceholder')}
                    rows={3}
                    className="w-full rounded-lg border border-border bg-background px-2.5 py-1.5 text-xs outline-none placeholder:text-muted-foreground/50 focus:ring-1 focus:ring-ring resize-y"
                  />
                </div>
              </div>
            )}

            {/* Active purpose badge */}
            {conversation && (
              <div className="flex items-center gap-2 border-b border-border px-4 py-2">
                <span className="text-sm">
                  {PURPOSE_ICONS[conversation.purpose]}
                </span>
                <span className="text-xs font-medium">
                  {t(PURPOSE_LABEL_KEYS[conversation.purpose])}
                </span>
                <span className="text-xs text-muted-foreground">
                  &middot; {ti('ai.messagesCount', { count: conversation.messages.length })}
                </span>
              </div>
            )}

            {/* Conversation area */}
            <div className="flex-1 overflow-y-auto px-4 py-3">
              {conversation?.messages
                .filter((m) => m.role !== 'system' && !m.isAutoGenerated)
                .map((msg, i) => (
                  <div
                    key={i}
                    className={`mb-3 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}
                  >
                    <div
                      className={`inline-block max-w-[85%] rounded-lg px-3 py-2 text-sm ${
                        msg.role === 'user'
                          ? 'bg-primary/10 text-foreground'
                          : 'bg-accent text-foreground'
                      }`}
                    >
                      <div className="whitespace-pre-wrap break-words">
                        {msg.role === 'assistant' ? renderMarkdown(msg.content) : msg.content}
                      </div>
                      <div className="mt-1 text-[10px] text-muted-foreground">
                        {new Date(msg.timestamp).toLocaleTimeString([], {
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </div>
                    </div>
                  </div>
                ))}

              {/* Streaming indicator */}
              {isGenerating && (
                <div className="mb-3 text-left">
                  <div className="inline-block max-w-[85%] rounded-lg bg-accent px-3 py-2 text-sm text-foreground">
                    {streamingText ? (
                      <div className="whitespace-pre-wrap break-words">
                        {renderMarkdown(streamingText)}
                        <span className="ml-0.5 inline-block animate-pulse">
                          |
                        </span>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1 text-muted-foreground">
                        <span className="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:0ms]" />
                        <span className="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:150ms]" />
                        <span className="inline-block h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:300ms]" />
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Error message */}
              {error && (
                <div className="mb-3 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-400">
                  {error}
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Input area */}
            <div className="border-t border-border px-4 py-3">
              {/* Post to chat button */}
              {lastResponse && !isGenerating && (
                <button
                  onClick={() => postToChat(lastResponse)}
                  className="mb-2 w-full rounded-md border border-purple-500/30 bg-purple-500/10 px-3 py-1.5 text-xs font-medium text-purple-400 transition hover:bg-purple-500/20"
                >
                  {t('ai.postToChat')}
                </button>
              )}

              <div className="flex items-end gap-2">
                <textarea
                  ref={textareaRef}
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder={
                    conversation
                      ? t('ai.followUpPlaceholder')
                      : t('ai.startConversationPlaceholder')
                  }
                  rows={1}
                  className="flex-1 resize-none rounded-lg border border-input bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus:ring-1 focus:ring-ring"
                />
                {isGenerating ? (
                  <button
                    onClick={abort}
                    className="shrink-0 rounded-lg bg-red-500/80 px-3 py-2 text-sm font-medium text-white transition hover:bg-red-500"
                  >
                    {t('common.stop')}
                  </button>
                ) : (
                  <button
                    onClick={handleSend}
                    disabled={!inputValue.trim()}
                    className="shrink-0 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground transition hover:opacity-90 disabled:opacity-40"
                  >
                    {t('common.send')}
                  </button>
                )}
              </div>
            </div>
          </>
        )}
      </div>
    </>
  )
}
