/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteRouteImport } from './routes/player/route'
import { Route as GmRouteRouteImport } from './routes/gm/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerSessionRouteImport } from './routes/player/session'
import { Route as PlayerJoinRouteImport } from './routes/player/join'
import { Route as GmTablesRouteImport } from './routes/gm/tables'
import { Route as GmStoresRouteImport } from './routes/gm/stores'
import { Route as GmSettingsRouteImport } from './routes/gm/settings'
import { Route as GmMonstersRouteImport } from './routes/gm/monsters'
import { Route as GmCreateRouteImport } from './routes/gm/create'
import { Route as GmCharactersRouteImport } from './routes/gm/characters'
import { Route as GmSessionSessionIdRouteImport } from './routes/gm/session.$sessionId'

const PlayerRouteRoute = PlayerRouteRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRouteRoute = GmRouteRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSessionRoute = PlayerSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerJoinRoute = PlayerJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const GmTablesRoute = GmTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmStoresRoute = GmStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmSettingsRoute = GmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmMonstersRoute = GmMonstersRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmCreateRoute = GmCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmCharactersRoute = GmCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmSessionSessionIdRoute = GmSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => GmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gm'
    | '/player'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/gm/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gm'
    | '/player'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/gm/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/gm'
    | '/player'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/gm/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GmRouteRoute: typeof GmRouteRouteWithChildren
  PlayerRouteRoute: typeof PlayerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/session': {
      id: '/player/session'
      path: '/session'
      fullPath: '/player/session'
      preLoaderRoute: typeof PlayerSessionRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/join': {
      id: '/player/join'
      path: '/join'
      fullPath: '/player/join'
      preLoaderRoute: typeof PlayerJoinRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/gm/tables': {
      id: '/gm/tables'
      path: '/tables'
      fullPath: '/gm/tables'
      preLoaderRoute: typeof GmTablesRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/stores': {
      id: '/gm/stores'
      path: '/stores'
      fullPath: '/gm/stores'
      preLoaderRoute: typeof GmStoresRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/settings': {
      id: '/gm/settings'
      path: '/settings'
      fullPath: '/gm/settings'
      preLoaderRoute: typeof GmSettingsRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/monsters': {
      id: '/gm/monsters'
      path: '/monsters'
      fullPath: '/gm/monsters'
      preLoaderRoute: typeof GmMonstersRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/create': {
      id: '/gm/create'
      path: '/create'
      fullPath: '/gm/create'
      preLoaderRoute: typeof GmCreateRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/characters': {
      id: '/gm/characters'
      path: '/characters'
      fullPath: '/gm/characters'
      preLoaderRoute: typeof GmCharactersRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/session/$sessionId': {
      id: '/gm/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/gm/session/$sessionId'
      preLoaderRoute: typeof GmSessionSessionIdRouteImport
      parentRoute: typeof GmRouteRoute
    }
  }
}

interface GmRouteRouteChildren {
  GmCharactersRoute: typeof GmCharactersRoute
  GmCreateRoute: typeof GmCreateRoute
  GmMonstersRoute: typeof GmMonstersRoute
  GmSettingsRoute: typeof GmSettingsRoute
  GmStoresRoute: typeof GmStoresRoute
  GmTablesRoute: typeof GmTablesRoute
  GmSessionSessionIdRoute: typeof GmSessionSessionIdRoute
}

const GmRouteRouteChildren: GmRouteRouteChildren = {
  GmCharactersRoute: GmCharactersRoute,
  GmCreateRoute: GmCreateRoute,
  GmMonstersRoute: GmMonstersRoute,
  GmSettingsRoute: GmSettingsRoute,
  GmStoresRoute: GmStoresRoute,
  GmTablesRoute: GmTablesRoute,
  GmSessionSessionIdRoute: GmSessionSessionIdRoute,
}

const GmRouteRouteWithChildren =
  GmRouteRoute._addFileChildren(GmRouteRouteChildren)

interface PlayerRouteRouteChildren {
  PlayerJoinRoute: typeof PlayerJoinRoute
  PlayerSessionRoute: typeof PlayerSessionRoute
}

const PlayerRouteRouteChildren: PlayerRouteRouteChildren = {
  PlayerJoinRoute: PlayerJoinRoute,
  PlayerSessionRoute: PlayerSessionRoute,
}

const PlayerRouteRouteWithChildren = PlayerRouteRoute._addFileChildren(
  PlayerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GmRouteRoute: GmRouteRouteWithChildren,
  PlayerRouteRoute: PlayerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
