/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteRouteImport } from './routes/player/route'
import { Route as GmRouteRouteImport } from './routes/gm/route'
import { Route as CampaignRouteRouteImport } from './routes/campaign/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign/index'
import { Route as PlayerSessionRouteImport } from './routes/player/session'
import { Route as PlayerJoinRouteImport } from './routes/player/join'
import { Route as GmTablesRouteImport } from './routes/gm/tables'
import { Route as GmStoresRouteImport } from './routes/gm/stores'
import { Route as GmSettingsRouteImport } from './routes/gm/settings'
import { Route as GmMonstersRouteImport } from './routes/gm/monsters'
import { Route as GmCreateRouteImport } from './routes/gm/create'
import { Route as GmCharactersRouteImport } from './routes/gm/characters'
import { Route as CampaignCampaignIdRouteImport } from './routes/campaign/$campaignId'
import { Route as CampaignCampaignIdIndexRouteImport } from './routes/campaign/$campaignId.index'
import { Route as GmSessionSessionIdRouteImport } from './routes/gm/session.$sessionId'
import { Route as CampaignCampaignIdMapRouteImport } from './routes/campaign/$campaignId.map'
import { Route as CampaignCampaignIdLoreRouteImport } from './routes/campaign/$campaignId.lore'
import { Route as CampaignCampaignIdContentRouteImport } from './routes/campaign/$campaignId.content'
import { Route as CampaignCampaignIdAiRouteImport } from './routes/campaign/$campaignId.ai'
import { Route as CampaignCampaignIdAdventureRouteImport } from './routes/campaign/$campaignId.adventure'

const PlayerRouteRoute = PlayerRouteRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRouteRoute = GmRouteRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRouteRoute = CampaignRouteRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const PlayerSessionRoute = PlayerSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerJoinRoute = PlayerJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const GmTablesRoute = GmTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmStoresRoute = GmStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmSettingsRoute = GmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmMonstersRoute = GmMonstersRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmCreateRoute = GmCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GmRouteRoute,
} as any)
const GmCharactersRoute = GmCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => GmRouteRoute,
} as any)
const CampaignCampaignIdRoute = CampaignCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignRouteRoute,
} as any)
const CampaignCampaignIdIndexRoute = CampaignCampaignIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignCampaignIdRoute,
} as any)
const GmSessionSessionIdRoute = GmSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => GmRouteRoute,
} as any)
const CampaignCampaignIdMapRoute = CampaignCampaignIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CampaignCampaignIdRoute,
} as any)
const CampaignCampaignIdLoreRoute = CampaignCampaignIdLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => CampaignCampaignIdRoute,
} as any)
const CampaignCampaignIdContentRoute =
  CampaignCampaignIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => CampaignCampaignIdRoute,
  } as any)
const CampaignCampaignIdAiRoute = CampaignCampaignIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => CampaignCampaignIdRoute,
} as any)
const CampaignCampaignIdAdventureRoute =
  CampaignCampaignIdAdventureRouteImport.update({
    id: '/adventure',
    path: '/adventure',
    getParentRoute: () => CampaignCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/campaign/$campaignId': typeof CampaignCampaignIdRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/campaign/': typeof CampaignIndexRoute
  '/campaign/$campaignId/adventure': typeof CampaignCampaignIdAdventureRoute
  '/campaign/$campaignId/ai': typeof CampaignCampaignIdAiRoute
  '/campaign/$campaignId/content': typeof CampaignCampaignIdContentRoute
  '/campaign/$campaignId/lore': typeof CampaignCampaignIdLoreRoute
  '/campaign/$campaignId/map': typeof CampaignCampaignIdMapRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
  '/campaign/$campaignId/': typeof CampaignCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/campaign': typeof CampaignIndexRoute
  '/campaign/$campaignId/adventure': typeof CampaignCampaignIdAdventureRoute
  '/campaign/$campaignId/ai': typeof CampaignCampaignIdAiRoute
  '/campaign/$campaignId/content': typeof CampaignCampaignIdContentRoute
  '/campaign/$campaignId/lore': typeof CampaignCampaignIdLoreRoute
  '/campaign/$campaignId/map': typeof CampaignCampaignIdMapRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteRouteWithChildren
  '/gm': typeof GmRouteRouteWithChildren
  '/player': typeof PlayerRouteRouteWithChildren
  '/campaign/$campaignId': typeof CampaignCampaignIdRouteWithChildren
  '/gm/characters': typeof GmCharactersRoute
  '/gm/create': typeof GmCreateRoute
  '/gm/monsters': typeof GmMonstersRoute
  '/gm/settings': typeof GmSettingsRoute
  '/gm/stores': typeof GmStoresRoute
  '/gm/tables': typeof GmTablesRoute
  '/player/join': typeof PlayerJoinRoute
  '/player/session': typeof PlayerSessionRoute
  '/campaign/': typeof CampaignIndexRoute
  '/campaign/$campaignId/adventure': typeof CampaignCampaignIdAdventureRoute
  '/campaign/$campaignId/ai': typeof CampaignCampaignIdAiRoute
  '/campaign/$campaignId/content': typeof CampaignCampaignIdContentRoute
  '/campaign/$campaignId/lore': typeof CampaignCampaignIdLoreRoute
  '/campaign/$campaignId/map': typeof CampaignCampaignIdMapRoute
  '/gm/session/$sessionId': typeof GmSessionSessionIdRoute
  '/campaign/$campaignId/': typeof CampaignCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/gm'
    | '/player'
    | '/campaign/$campaignId'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/campaign/'
    | '/campaign/$campaignId/adventure'
    | '/campaign/$campaignId/ai'
    | '/campaign/$campaignId/content'
    | '/campaign/$campaignId/lore'
    | '/campaign/$campaignId/map'
    | '/gm/session/$sessionId'
    | '/campaign/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gm'
    | '/player'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/campaign'
    | '/campaign/$campaignId/adventure'
    | '/campaign/$campaignId/ai'
    | '/campaign/$campaignId/content'
    | '/campaign/$campaignId/lore'
    | '/campaign/$campaignId/map'
    | '/gm/session/$sessionId'
    | '/campaign/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/gm'
    | '/player'
    | '/campaign/$campaignId'
    | '/gm/characters'
    | '/gm/create'
    | '/gm/monsters'
    | '/gm/settings'
    | '/gm/stores'
    | '/gm/tables'
    | '/player/join'
    | '/player/session'
    | '/campaign/'
    | '/campaign/$campaignId/adventure'
    | '/campaign/$campaignId/ai'
    | '/campaign/$campaignId/content'
    | '/campaign/$campaignId/lore'
    | '/campaign/$campaignId/map'
    | '/gm/session/$sessionId'
    | '/campaign/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRouteRoute: typeof CampaignRouteRouteWithChildren
  GmRouteRoute: typeof GmRouteRouteWithChildren
  PlayerRouteRoute: typeof PlayerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/player/session': {
      id: '/player/session'
      path: '/session'
      fullPath: '/player/session'
      preLoaderRoute: typeof PlayerSessionRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/join': {
      id: '/player/join'
      path: '/join'
      fullPath: '/player/join'
      preLoaderRoute: typeof PlayerJoinRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/gm/tables': {
      id: '/gm/tables'
      path: '/tables'
      fullPath: '/gm/tables'
      preLoaderRoute: typeof GmTablesRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/stores': {
      id: '/gm/stores'
      path: '/stores'
      fullPath: '/gm/stores'
      preLoaderRoute: typeof GmStoresRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/settings': {
      id: '/gm/settings'
      path: '/settings'
      fullPath: '/gm/settings'
      preLoaderRoute: typeof GmSettingsRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/monsters': {
      id: '/gm/monsters'
      path: '/monsters'
      fullPath: '/gm/monsters'
      preLoaderRoute: typeof GmMonstersRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/create': {
      id: '/gm/create'
      path: '/create'
      fullPath: '/gm/create'
      preLoaderRoute: typeof GmCreateRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/gm/characters': {
      id: '/gm/characters'
      path: '/characters'
      fullPath: '/gm/characters'
      preLoaderRoute: typeof GmCharactersRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/campaign/$campaignId': {
      id: '/campaign/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaign/$campaignId'
      preLoaderRoute: typeof CampaignCampaignIdRouteImport
      parentRoute: typeof CampaignRouteRoute
    }
    '/campaign/$campaignId/': {
      id: '/campaign/$campaignId/'
      path: '/'
      fullPath: '/campaign/$campaignId/'
      preLoaderRoute: typeof CampaignCampaignIdIndexRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
    '/gm/session/$sessionId': {
      id: '/gm/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/gm/session/$sessionId'
      preLoaderRoute: typeof GmSessionSessionIdRouteImport
      parentRoute: typeof GmRouteRoute
    }
    '/campaign/$campaignId/map': {
      id: '/campaign/$campaignId/map'
      path: '/map'
      fullPath: '/campaign/$campaignId/map'
      preLoaderRoute: typeof CampaignCampaignIdMapRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
    '/campaign/$campaignId/lore': {
      id: '/campaign/$campaignId/lore'
      path: '/lore'
      fullPath: '/campaign/$campaignId/lore'
      preLoaderRoute: typeof CampaignCampaignIdLoreRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
    '/campaign/$campaignId/content': {
      id: '/campaign/$campaignId/content'
      path: '/content'
      fullPath: '/campaign/$campaignId/content'
      preLoaderRoute: typeof CampaignCampaignIdContentRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
    '/campaign/$campaignId/ai': {
      id: '/campaign/$campaignId/ai'
      path: '/ai'
      fullPath: '/campaign/$campaignId/ai'
      preLoaderRoute: typeof CampaignCampaignIdAiRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
    '/campaign/$campaignId/adventure': {
      id: '/campaign/$campaignId/adventure'
      path: '/adventure'
      fullPath: '/campaign/$campaignId/adventure'
      preLoaderRoute: typeof CampaignCampaignIdAdventureRouteImport
      parentRoute: typeof CampaignCampaignIdRoute
    }
  }
}

interface CampaignCampaignIdRouteChildren {
  CampaignCampaignIdAdventureRoute: typeof CampaignCampaignIdAdventureRoute
  CampaignCampaignIdAiRoute: typeof CampaignCampaignIdAiRoute
  CampaignCampaignIdContentRoute: typeof CampaignCampaignIdContentRoute
  CampaignCampaignIdLoreRoute: typeof CampaignCampaignIdLoreRoute
  CampaignCampaignIdMapRoute: typeof CampaignCampaignIdMapRoute
  CampaignCampaignIdIndexRoute: typeof CampaignCampaignIdIndexRoute
}

const CampaignCampaignIdRouteChildren: CampaignCampaignIdRouteChildren = {
  CampaignCampaignIdAdventureRoute: CampaignCampaignIdAdventureRoute,
  CampaignCampaignIdAiRoute: CampaignCampaignIdAiRoute,
  CampaignCampaignIdContentRoute: CampaignCampaignIdContentRoute,
  CampaignCampaignIdLoreRoute: CampaignCampaignIdLoreRoute,
  CampaignCampaignIdMapRoute: CampaignCampaignIdMapRoute,
  CampaignCampaignIdIndexRoute: CampaignCampaignIdIndexRoute,
}

const CampaignCampaignIdRouteWithChildren =
  CampaignCampaignIdRoute._addFileChildren(CampaignCampaignIdRouteChildren)

interface CampaignRouteRouteChildren {
  CampaignCampaignIdRoute: typeof CampaignCampaignIdRouteWithChildren
  CampaignIndexRoute: typeof CampaignIndexRoute
}

const CampaignRouteRouteChildren: CampaignRouteRouteChildren = {
  CampaignCampaignIdRoute: CampaignCampaignIdRouteWithChildren,
  CampaignIndexRoute: CampaignIndexRoute,
}

const CampaignRouteRouteWithChildren = CampaignRouteRoute._addFileChildren(
  CampaignRouteRouteChildren,
)

interface GmRouteRouteChildren {
  GmCharactersRoute: typeof GmCharactersRoute
  GmCreateRoute: typeof GmCreateRoute
  GmMonstersRoute: typeof GmMonstersRoute
  GmSettingsRoute: typeof GmSettingsRoute
  GmStoresRoute: typeof GmStoresRoute
  GmTablesRoute: typeof GmTablesRoute
  GmSessionSessionIdRoute: typeof GmSessionSessionIdRoute
}

const GmRouteRouteChildren: GmRouteRouteChildren = {
  GmCharactersRoute: GmCharactersRoute,
  GmCreateRoute: GmCreateRoute,
  GmMonstersRoute: GmMonstersRoute,
  GmSettingsRoute: GmSettingsRoute,
  GmStoresRoute: GmStoresRoute,
  GmTablesRoute: GmTablesRoute,
  GmSessionSessionIdRoute: GmSessionSessionIdRoute,
}

const GmRouteRouteWithChildren =
  GmRouteRoute._addFileChildren(GmRouteRouteChildren)

interface PlayerRouteRouteChildren {
  PlayerJoinRoute: typeof PlayerJoinRoute
  PlayerSessionRoute: typeof PlayerSessionRoute
}

const PlayerRouteRouteChildren: PlayerRouteRouteChildren = {
  PlayerJoinRoute: PlayerJoinRoute,
  PlayerSessionRoute: PlayerSessionRoute,
}

const PlayerRouteRouteWithChildren = PlayerRouteRoute._addFileChildren(
  PlayerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRouteRoute: CampaignRouteRouteWithChildren,
  GmRouteRoute: GmRouteRouteWithChildren,
  PlayerRouteRoute: PlayerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
